#!/bin/bash

cpus="$(nproc)"

# loop on all pdf repositories under gerda/distorted
counter=1
for f in `find gerda-pdfs/distorted -name '*.tar.xz'`; do
    dir=`dirname $f`/`basename $f .tar.xz`
    [ ! -d $dir ] \
        && echo "ERROR: it seems that you didn't run 'get-pdfs' first" \
        && exit 1

    # collect all PDFs after LAr veto
    filelist=""
    echo "Queuing $dir"
    for ff in `find $dir -name '*.root'`; do
        filelist="$filelist $ff"
    done

    # and give the list to ROOT
    ./ROOTroutine.C "$filelist" > /dev/null &

    if [[ $counter == $cpus ]]; then
        echo "INFO: waiting for the following background jobs to end..."
        jobs
        for job in `jobs -rp`; do
            wait $job
        done
        counter=1
    else
        let counter++
    fi
done

./take_ratio.C \
    gerda-pdfs/gerda-pdfs-2nufit-best/larveto/outer_fibers/Ac228/pdf-larveto-outer_fibers-Ac228.root \
    gerda-pdfs/gerda-pdfs-2nufit-best/ge_holders/ge_holders_all/Ac228/pdf-ge_holders-ge_holders_all-Ac228.root \
    lar/M1_enrBEGe lar/M1_enrCoax \
    distortions/pdf-Ac228-holders_vs_fibers.root

./take_ratio.C \
    gerda-pdfs/gerda-pdfs-2nufit-best/larveto/copper_shroud/K40/pdf-larveto-copper_shroud-K40.root \
    gerda-pdfs/gerda-pdfs-2nufit-best/electronics/cc3/K40/pdf-electronics-cc3-K40.root \
    lar/M1_enrBEGe lar/M1_enrCoax \
    distortions/pdf-K40_far-cc3_vs_copper_shroud.root

./take_ratio.C \
    gerda-pdfs/gerda-pdfs-2nufit-best/gedet/pplus_bege/K42/pdf-gedet-pplus_bege-K42.root \
    gerda-pdfs/gerda-pdfs-2nufit-best/gedet/nplus_bege/K42/pdf-gedet-nplus_bege-K42.root \
    lar/M1_enrBEGe lar/M1_enrCoax \
    distortions/pdf-K42_close-nplus_bege_vs_pplus_bege.root

./take_ratio.C \
    gerda-pdfs/gerda-pdfs-2nufit-best/lar/above_array/K42/pdf-lar-above_array-K42.root \
    gerda-pdfs/gerda-pdfs-2nufit-best/lar/sur_array/K42/pdf-lar-sur_array-K42.root \
    lar/M1_enrBEGe lar/M1_enrCoax \
    distortions/pdf-K42_far-sur_array_vs_above_array.root

./take_ratio.C \
    gerda-pdfs/gerda-pdfs-2nufit-best/cables/cables_all/K40/pdf-cables-cables_all-K40.root \
    gerda-pdfs/gerda-pdfs-2nufit-best/minishroud/ms_all/K40/pdf-minishroud-ms_all-K40.root \
    lar/M1_enrBEGe lar/M1_enrCoax \
    distortions/pdf-K40_close-minishroud_vs_cables.root

./take_ratio.C \
    gerda-pdfs/gerda-pdfs-2nufit-best/ge_holders/ge_holders_all/K40/pdf-ge_holders-ge_holders_all-K40.root \
    gerda-pdfs/gerda-pdfs-2nufit-best/minishroud/ms_all/K40/pdf-minishroud-ms_all-K40.root \
    lar/M1_enrBEGe lar/M1_enrCoax \
    distortions/pdf-K40_close-minishroud_vs_holders.root

./Bi212Tl208_distortion.C
